name: Java CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  upload-designite-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Clone tushartushar/DesigniteJava
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'tushartushar'
          repository: 'DesigniteJava'
      - name: Create DesigniteJava .jar
        run: |
          cd DesigniteJava
          mvn package -Dmaven.test.skip
          pwd
      - name: Upload DesigniteJava .jar
        uses: actions/upload-artifact@v3
        with:
          name: designite-java
          path: DesigniteJava/target/DesigniteJava.jar
  report:
    runs-on: ubuntu-latest
    needs: upload-designite-artifact
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn -B test
      - name: Run Coverage
        run: |
            mvn jacoco:report
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
      - name: Run check style to show in action
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
      - name: Run checkstyle
        run: mvn checkstyle:checkstyle
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: designite-java
      - name: Run
        run:  java -jar DesigniteJava.jar -i ./src -o ./target/designite
      - name: Get report info
        id: reportsInfo
        uses: tupac-rocher/mvn-format-xml-reports@v1.1
        with:
          checkstyle-result-xml: ${{ github.workspace }}/target/checkstyle-result.xml
          designite-result-csv: ${{ github.workspace }}/target/designite/designCodeSmells.csv
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Total coverage ${{ steps.jacoco.outputs.coverage-overall }}
            Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}
            ${{ steps.reportsInfo.outputs.checkstyle-comment }}
            ${{ steps.reportsInfo.outputs.designite-comment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


